name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root (for Husky if needed)
        run: npm ci

      - name: Install backend deps
        run: npm --prefix backend ci

      - name: Install frontend deps
        run: npm --prefix frontend ci

      - name: Lint backend
        run: npm run lint:backend

      - name: Lint frontend
        run: npm run lint:frontend

      # Optional: type-check/build
      - name: Build backend
        run: npm --prefix backend run build

      - name: Build frontend
        run: npm --prefix frontend run build
